ARG PYTHON_BASE_VERSION=3.9.8
FROM python:${PYTHON_BASE_VERSION}-slim

ARG ASDF_VERSION=0.8.1

COPY asdf-install-toolset.sh /usr/local/bin/asdf-install-toolset

RUN apt-get update -q && \
    apt-get install -y --no-install-recommends git curl ca-certificates unzip gnupg \
    && useradd -m -s /usr/bin/bash -u 1000 asdf \
    && rm -rf /var/lib/apt/lists/* /var/cache/* \
    && install asdf-install-toolset /usr/local/bin \
    && rm asdf-install-toolset \
    && ln -s /usr/bin/env /bin/env || true

SHELL ["/bin/bash", "-l", "-c"]

WORKDIR /home/asdf
USER asdf

ENV ASDF_DATA_DIR="/home/asdf/.asdf-data" 
ENV PATH="${PATH}:${ASDF_DATA_DIR}/shims:${ASDF_DATA_DIR}/bin"

RUN git clone --depth 1 https://github.com/asdf-vm/asdf.git $HOME/.asdf \
    && echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc \
    && echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.profile \
    && source ~/.bashrc \
    && mkdir -p "${ASDF_DATA_DIR}"
